### ISSUE TITLE
train an AM model on the DFKI cluster

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pie-document-level#100]
Chose an experiment from `configs/experiments` that is related to argumentation mining and execute a training run at the DFKI GPU cluster. Document any obstacles. Post the final location of the trained model (`model_save_dir`) to this issue. 

Notes:
 - see #99 for setup instructions
 - use `trainer=gpu` to actually train on the GPU

**Comment by jk-tripathy** [comment]
/home/jtripathy/pie-document-level/models/dataset-cdcp/task-adus/2023-08-16_21-36-53

**Comment by ArneBinder** [comment]
Can you also post the commands that you used?

**Comment by jk-tripathy** [comment]
wrapper python src/train.py trainer=gpu experiment=cdcp_adus

wrapper is just an alias I created for pegasus-bridle/wrapper.sh

**Comment by ArneBinder** [comment]
OK, cool, thanks!
