### ISSUE TITLE
predict with an AM model on the cluster and evaluate the results

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pie-document-level#101]
Use the model trained in #100 to create predictions. Document the output location in this issue. Evaluate the predictions and also document the results here (the content of `job_return_value.md`).

**Comment by jk-tripathy** [comment]
|           |        0 |
|:----------|---------:|
| test/loss | 0.893989 |
| test/f1   | 0.810766 |

**Comment by ArneBinder** [comment]
Can you also post the commands that you used?

**Comment by jk-tripathy** [comment]
wrapper python src/evaluate.py trainer=gpu dataset=cdcp_prepared model_name_or_path=models/dataset-cdcp/task-adus/2023-08-16_21-36-53/

**Comment by ArneBinder** [comment]
For this issue, I meant that you try out the whole process as described in the readme:
1. train: `python src/train.py ...` (this is already covered in #100)
2. predict: ~`python src/train.py ...`~ EDIT: `python src/predict.py ...`
3. evaluate the predicted output: `python src/evaluate_documents.py ...` (this allows to use metrics that are not implemented in the model, which is for now just the (span-based) F1, but we may add more in the future)

Sorry, that was really not clear from the issue description.

**Comment by jk-tripathy** [comment]
Oh understood

**Comment by jk-tripathy** [comment]
for step 2 do you mean `src/predict.py` ?

**Comment by jk-tripathy** [comment]
2. `wrapper python src/predict.py +pipeline.device=0 dataset=cdcp_prepared model_name_or_path=models/dataset-cdcp/task-adus/2023-08-16_21-36-53/`

3. `python src/evaluate_documents.py metric=f1 metric.layer=entities +dataset.data_dir=predictions/default/2023-08-17_00-05-43/ +dataset.document_type=src.document.types.DocumentWithEntitiesRelationsAndLabeledPartitions`

Output: 
entities:
|       |    f1 |     p |     r |
|:------|------:|------:|------:|
| MICRO | 0.533 | 0.453 | 0.646 |

**Comment by ArneBinder** [comment]
Thanks! Two last things: Can you also calculate the per-label performance? And how good is this result (compare with SOTA)?

**Comment by jk-tripathy** [comment]
Per Label Performance of the model:

|           |    f1 |     p |     r |
|:----------|------:|------:|------:|
| MACRO     | 0.42  | 0.362 | 0.51  |
| MICRO     | 0.533 | 0.453 | 0.646 |
| fact      | 0.302 | 0.222 | 0.47  |
| testimony | 0.587 | 0.512 | 0.689 |
| value     | 0.55  | 0.481 | 0.641 |
| policy    | 0.663 | 0.593 | 0.752 |
| reference | 0     | 0     | 0     |

**Comment by jk-tripathy** [comment]
[SOTA paper](https://aclanthology.org/2021.acl-long.497/)


|           |    f1 |
|:----------|------:|
| MACRO     | 0.825 | 
| fact      | 0.583 |
| testimony | 0.849 |
| value     | 0.832  |
| policy    | 0.863 |
| reference | 1.0 |

**Comment by ArneBinder** [comment]
Thanks!
Please create the two new issues in the respective repos and link them from here: 1) errors/missing description in the inference section of README.md, and 2) the problem with conda.
