### ISSUE TITLE
try multi-GPU training on the cluster

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pie-document-level#105]
via `trainer=ddp`

Maybe related:
 - https://github.com/facebookresearch/hydra/issues/2070
 - #6

**Comment by jk-tripathy** [comment]
I combined this task with #106 and trained on multi GPU with multi run.

Command: `wrapper python src/train.py trainer=ddp trainer.devices=2 seed=42,43 --multirun`

The saved models can be found at:
- `/home/jtripathy/pie-document-level/2023-08-23_13-32-38`
- `/home/jtripathy/pie-document-level/2023-08-23_13-42-21`

**Comment by ArneBinder** [comment]
Ok, cool! can you also report the location of the predictions and the output of evaluate documents?

**Comment by jk-tripathy** [comment]
I got a bit sidetracked with issue #6 since the saved models are probably not at the best checkpoints. I'll try to get both done by EOD. Unless you want me to first finish off issue #106?

**Comment by ArneBinder** [comment]
Yes, please finish #106 first. This should be a fast catch and is just so that you get used to the workflow. The  models are not useful at all because they are for the conll2003 dataset which we do not need (no argumentation data). This is the default when you do not define a dataset (or experiment, which internally defines a dataset).

**Comment by jk-tripathy** [comment]
Right got it, ill get started on it now then
