### ISSUE TITLE
try multi-run training+inference+evaluation

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pie-document-level#106]
The outcome should be to be familiar with this and maybe a workflow how to do this efficiently in the future.

**Comment by jk-tripathy** [comment]
Train Command: `wrapper python src/train.py trainer=gpu seed=42,43 --multirun`
Inference Command: `wrapper python src/predict.py dataset=conll2003 model_name_or_path=models/cdcp_adu_test/2023-08-23_22-20-27/,models/cdcp_adu_test/2023-08-23_22-32-31 +pipeline.device=0 +tags="[test]" --multirun`
Evaluate Docs Command: `wrapper python src/evaluate_documents.py metric=f1 metric.layer=entities +dataset.document_type=src.document.types.DocumentWithEntitiesRelationsAndLabeledPartitions +dataset.data_dir=predictions/default/2023-08-23_23-39-50/,predictions/default/2023-08-23_23-41-33/ --multirun`

Output:
|    |   ('test', 'MICRO', 'f1') |   ('test', 'MICRO', 'p') |   ('test', 'MICRO', 'r') |
|---:|--------------------------:|-------------------------:|-------------------------:|
|  0 |                  0.892512 |                 0.8791   |                 0.906339 |
|  1 |                  0.894984 |                 0.880569 |                 0.90988  |

Output Aggregated:
|                         |      25% |      50% |      75% |   count |      max |     mean |      min |        std |
|:------------------------|---------:|---------:|---------:|--------:|---------:|---------:|---------:|-----------:|
| ('test', 'MICRO', 'f1') | 0.89313  | 0.893748 | 0.894366 |       2 | 0.894984 | 0.893748 | 0.892512 | 0.00174852 |
| ('test', 'MICRO', 'p')  | 0.879467 | 0.879835 | 0.880202 |       2 | 0.880569 | 0.879835 | 0.8791   | 0.00103857 |
| ('test', 'MICRO', 'r')  | 0.907224 | 0.908109 | 0.908994 |       2 | 0.90988  | 0.908109 | 0.906339 | 0.00250392 |

**Comment by ArneBinder** [comment]
looks good! Did you also try to use the functionality introduced in #117?

**Comment by jk-tripathy** [comment]
Not yet, though I'm not sure i quite understand how to use the new flags. Does the `serializer/path` automatically go through all the different dirs to get to the `job_return_value.json`?

**Comment by ArneBinder** [comment]
You can anderstand `LOAD_(MULTI_)ARG` as a method with one mandatory argument (the path to the json file) and one optional argument (the path of keys inside the json), both separated with colons. So, you need to give the path to the `job_return_value.json` and then with the path of keys you can define what value out of the json will be used. Or what exactly do you mean?

**Comment by jk-tripathy** [comment]
I'm unsure about what `job_return_value.json` you mean in the predictions dir. I only have access to the `documents.jsonl` which is fed into the `evaluate_documents.py` by setting `dataset.data_dir`

**Comment by jk-tripathy** [comment]
wait my bad, we're passing in the logs and not the actual predictions. i got it now

**Comment by jk-tripathy** [comment]
yeah i got how it works now
Command: `wrapper python src/evaluate_documents.py metric=f1 metric.layer=entities +dataset.document_type=src.document.types.DocumentWithEntitiesRelationsAndLabeledPartitions +dataset.data_files.test=LOAD_MULTI_ARG:logs/prediction/multiruns/default/2023-08-23_23-39-49/job_return_value.json:serializer/path --multirun`
