### ISSUE TITLE
README Fix for Evaluate Serialized Documents 

### ISSUE THREAD

**Issue by jk-tripathy** [ArneBinder/pie-document-level#107]
The current command to evaluate serialized jsonl files is broken/outdated.

Suggested fix: 
`python src/evaluate_documents.py metric=f1 metric.layer=entities +dataset.data_dir=PATH/TO/DIR/WITH/SPLITS +dataset.document_type=TYPE/OF/DOCUMENT/IN/JSONL/FILE`

**Comment by ArneBinder** [comment]
@jatinkarthik-tripathy Thanks for reporting this! Was there any other unclearity that has created an obstacle for you? I think we talked about sth in our last meeting, but I do not fully recap.

**Comment by jk-tripathy** [comment]
@ArneBinder the other issue was the one with pegasus bridle and conda env on the container. Ive already created an issue for that.
