### ISSUE TITLE
Out of Memory (OOM) issue when hparam tuning using optuna

### ISSUE THREAD

**Issue by jk-tripathy** [ArneBinder/pie-document-level#173]
Sometimes, the hparam search fails when running the optuna configs. This issue does not raise up when dry running the process using `fast_dev_run=True`. 
- While an easily reproducible test has not been found yet, the search only seems to break while the base model is being tuned, and does not throw the OOM while the base model remains frozen. 
- The error occurs regardless of whether the trainer is set to a single GPU or multi GPU DDP strategy.

The actual error is below:

```markdown
python src/train.py trainer=gpu +trainer.fast_dev_run=false model=token_classification_with_seq2seq_encoder_and_crf datamodule.batch_size=10 experiment=sciarg_adus hparams_search=bert_tuned logger.wandb.project=bert_tuned
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=843956.0. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: kersey: task 0: Out Of Memory
srun: launch/slurm: _step_signal: Terminating StepId=843956.0
```

**Comment by ArneBinder** [comment]
Do you know after how many runs it crashed? 

Can you check if this also happens if you execute a simple `--multirun` command that does (more or less) the same? E.g. calling sth like this:
```bash
python src/train.py trainer=gpu \
+trainer.fast_dev_run=false \
model=token_classification_with_seq2seq_encoder_and_crf \
datamodule.batch_size=10 \
experiment=sciarg_adus \
logger.wandb.project=bert_tuned \
transformer_model=bert-large-uncased,roberta-base,allenai/scibert_scivocab_uncased \
model.learning_rate=5e-5,3e-5,2e-5,3e-4,1e-4 \
+model.task_learning_rate=5e-5,3e-5,2e-5,3e-4,1e-4 \
+model.freeze_base_model=false \
--multirun
```
instead of the command from the issue description.

And what do you think about doing the HP search individually per model (e.g. `bert-large-uncased`, `roberta-base`, ...)? Maybe just in the beginning to get the first results and to better understand the error?

**Comment by jk-tripathy** [comment]
The number of runs before it crashes is wildly varied (I've seen runs fail at run 13 and one time it failed at run 97). 
The multirun idea seems cool, ill use that along with single models to just get the ball rolling and to get the results

**Comment by ArneBinder** [comment]
> The number of runs before it crashes is wildly varied (I've seen runs fail at run 13 and one time it failed at run 97). 

ok, understood.

>The multirun idea seems cool, ill use that along with single models to just get the ball rolling and to get the results

cool, thanks!

**Comment by jk-tripathy** [comment]
This issue is possibly the same as issue #67. Further testing is being done to see if the model is not being offloaded when it is supposed to be. If this is the case, it may be because Optuna uses multirun, which uses joblib. Joblib is known not to release memory until all jobs are done, as seen in this [thread](https://github.com/NVIDIA/DALI/issues/3480#issuecomment-1655842569).

A possible fix may be [this](https://stackoverflow.com/questions/57858433/how-to-clear-gpu-memory-after-pytorch-model-training-without-restarting-kernel).

**Comment by jk-tripathy** [comment]
Upon further testing, it looks like the model does get offloaded.

GPU memory when `validate=false`
![image](https://github.com/ArneBinder/pie-document-level/assets/39101018/24c3c83a-d8fa-4934-ab54-fb04aa878c00)

GPU memory when `validate=true`
![image](https://github.com/ArneBinder/pie-document-level/assets/39101018/79ef0e5c-50af-4304-9c06-50a573e87346)

In both cases, the models being trained are in this order: `roberta-base`, `bert-large-uncased`, and `roberta-base`. And the next model that throws the OOM error is `bert-large-uncased`

**Comment by jk-tripathy** [comment]
Possible solutions to this issue could be:
- decrease the batch size
- train `bert-large-uncased` separately
- use `bert-base` instead to decrease the overall memory size. 

Ill look into what makes the most sense and add a comment explaining the choice

**Comment by jk-tripathy** [comment]
Looking into this further, there should be no extra benefit gained from using `bert-large-uncased` when we already use `roberta-base`. So it makes more sense to replace `bert-large-uncased` with `bert-base` and increase the batch size so that all the models use the GPU more effectively
